

# -------------------------> vertx线程池配置, -1表示自动配置
vertx:
  eventLoopPoolSize: -1
  workerPoolSize: -1

# -------------------------> http参数配置
http:
  port: 9238              # 端口号
  auth: false             # 是否开启权限校验
  instance: 1             # 部署实例数 (有默认值,可选配置ֵ)
  indexPage: index.html   # 首页文件 (有默认值,可选配置ֵ)
  webRoot: dist           # 静态自愿根目录 (有默认值,可选配置ֵ)
  annoPermissions:        # 允许匿名访问的url (*ͨ通配所有,其余情况请使用精确路径,或者修改MyPermissionStrategyImpl重写权限校验规则)
    - POST:/login